### ISSUE TITLE
Investigating Aries RFC's and DIDComm v2 overlap

### ISSUE THREAD

**Issue by Arxcis** [DIN-Foundation/bcs-ntnu-2021#27]
## Background
I have been spending some time lately researching the [Aries RFC's](https://github.com/hyperledger/aries-rfcs/blob/master/index.md), and trying to look for overlapping with [the new Identity Fondation-hosted DIDComm v2](https://identity.foundation/didcomm-messaging/spec/)

## Aries DIDComm RFC's overlapping with DIDComm v2

- Aries RFC 0003 Protocols - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/README.md
- Aries RFC 0005 Didcomm - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0005-didcomm/README.md
- Aries RFC 0019 Encryption envelope - https://github.com/hyperledger/aries-rfcs/blob/master/features/0019-encryption-envelope/README.md
- Aries RFC 0025 Didcomm transports - https://github.com/hyperledger/aries-rfcs/blob/master/features/0025-didcomm-transports/README.md
- Aries RFC 0046 Mediators and relays - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md

## Aries DIDComm RFC's partially overlapping 
- Aries RFC 0021 Didcomm message anatomy - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0021-didcomm-message-anatomy/README.md
- Aries RFC 0160 Connection protocol - https://github.com/hyperledger/aries-rfcs/blob/master/features/0160-connection-protocol/README.md
 
## Aries DIDComm RFC's not overlapping with DIDComm v2

- Aries RFC 0008 Message id and threading - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0008-message-id-and-threading/README.md
- Aries RFC 0011 Decorators - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0011-decorators/README.md
- Aries RFC 0020 Message types - https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0020-message-types/README.md

**Comment by Arxcis** [comment]
Here is my question:

[Aries RFC's](https://github.com/hyperledger/aries-rfcs/blob/master/index.md) can be categorized into 2 broad categories:
1. Aries RFC's which are inside the scope of DIDComm v2
2. Aries RFC's which are outside of the scope of DIDComm v2

Is it possible to make the distinction between the RFC's which are inside, and the RFC's which are outside crystal clear? Will this distinction be useful to the community, to make it easier to know which RFC's will receive continued support, and which will be deprecated after DIDComm v2 has landed?

**Comment by vongohren** [comment]
@Arxcis I do think one important thing to think about and mention is, how does this affect interopability. What are these non overlapping RFCs, and what features might that affect the interopable communication?

**Comment by vongohren** [comment]
One interessting thought when venturing into didcom might be this comment: https://github.com/uport-project/veramo/discussions/420#discussioncomment-517010
